package:
  name: scotch_esmumps
  version: "6.0.0"

source:
  fn: scotch_6.0.0_esmumps.tar.gz
  url: http://gforge.inria.fr/frs/download.php/file/31832/scotch_6.0.0_esmumps.tar.gz
  md5: c50d6187462ba801f9a82133ee666e8e
  patches:
    - clock_gettime.patch [osx]

build:
  number: 1

about:
  home: http://www.labri.fr/perso/pelegrin/scotch/
  license: CeCILL-C
